version: "3.8"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: tatarby-frontend
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://localhost:8000/graphql/
      - PORT=5173
